### ISSUE TITLE
Stub Email functionality

### ISSUE THREAD

**Issue by tmwbook** [sigmapi-gammaiota/sigmapi-web#136]
Right now if an action tries to send an email in dev it will error out. I believe there is a way to change this in the middleware settings to make the emails just print to terminal.

**Comment by tmwbook** [comment]
Currently the only place I have seen this is in the Standards app when trying to approve a summon request

**Comment by CJUnderhill** [comment]
Addressed in: 8acaaaadedbee35ac51b9d5bc86056066b01e9e0.
