### ISSUE TITLE
Analytics widget should not be loaded in development.

### ISSUE THREAD

**Issue by austintrose** [sigmapi-gammaiota/sigmapi-web#16]
Statistics will be inaccurate, since it counts pageviews when I click around in development.

You should add a check for `not settings.DEBUG` in the template.

**Comment by Rdbaker** [comment]
It'd probably be better to have logic that say "only load this in production" rather than "don't load this in development" so that if you ever have any other settings (staging, local, etc.) you don't need to update the logic

**Comment by austintrose** [comment]
True. It's sometimes helpful to turn off `DEBUG` in dev, as well.

We might just want to add an `is_production = True` to the production settings file.
