### ISSUE TITLE
Write Tests

### ISSUE THREAD

**Issue by tmwbook** [sigmapi-gammaiota/sigmapi-web#70]
Testing a web app is hard.  But as we add more features and restructure the site, it is important that we have tests to save us time on manually testing every function of the site.  Django has a getting started [guide](https://docs.djangoproject.com/en/1.11/topics/testing/) that we can use.  This is a much bigger assignment that should be done during the school year to increase communication between those working on it.

**Comment by kdmccormick** [comment]
HAHAHAHAHAHAHAHAHA

**Comment by kdmccormick** [comment]
In all seriousness though, they would be nice to have, but it will require an in-depth discussion on the quantity and type of tests would actually benefit us while not taking too much time away from features that would benefit the brotherhood.
